# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 02:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='st_work',
            name='idSTFolio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='server.St_folio'),
        ),
    ]
