# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 10:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20170728_0250'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='st_folio',
            unique_together=set([]),
        ),
    ]
