# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-12 23:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_auto_20170912_2249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='folio',
            options={'verbose_name_plural': '6. Creaci\xf3n de Folio'},
        ),
        migrations.AlterModelOptions(
            name='pro',
            options={'verbose_name_plural': '3. Creaci\xf3n de Profesional'},
        ),
        migrations.AlterModelOptions(
            name='st',
            options={'verbose_name_plural': '5. Creaci\xf3n de ST'},
        ),
        migrations.AlterModelOptions(
            name='st_folio',
            options={'verbose_name_plural': '2. ST y Folios asociados'},
        ),
        migrations.AlterModelOptions(
            name='st_work',
            options={'verbose_name_plural': '1. Obras asociadas'},
        ),
        migrations.AlterModelOptions(
            name='work',
            options={'verbose_name_plural': '4. Creaci\xf3n de Obra'},
        ),
    ]
